@startuml Capteur
title Diagramme de Séquence - Détection des données frauduleuses des capteurs privés

actor "Administrateur" as admin

participant "CLI" as cli

participant "AuthService" as auth
participant "AuthDataAccess" as authdata

participant "Statistics" as service
participant "AdminServices" as adminservice

participant "DataLoader" as dl
participant "UserDataAccess" as uda

== Authentification d'un utilisateur ==
admin -> cli : 1. Authentification
activate cli
cli -> auth : 2. login(login, mdp)

    activate auth
        auth -> authdata : 3. findCredential(login)

        activate authdata
            authdata -> auth : 4. Credentials
        deactivate authdata

        create "s :  Session(ADMIN)" as s
        auth -> s : 5. <<create>>
        auth --> cli : 6. s
        cli --> admin : 7. Authentification réussie

== Chargement des capteurs ==
    cli -> dl  : 8. loadData(s.userType)
    activate dl
    create "s1 : Sensor" as s1
    dl -> s1 : <<create>>
    dl --> cli  : 9. capteurs fiables et leurs mesures chargés
    deactivate dl

== Chargement des cleaners ==
    cli -> dl  : 10. loadData(s.userType)
    activate dl
    create "c1 : Cleaner" as c1
    dl -> c1 : <<create>>
    dl --> cli  : 11. purificateurs chargés
    deactivate dl

== Analyse du capteur ==
    admin -> cli : 12. analyzeSensor(sensorId, date_debut, date_fin)
    cli -> service : 13 analyzeSensor(SensorID, date_debut, date_fin)
    activate service
    service -> auth : 14. checkRequiredRole(USER)
    auth --> service : 15. ADMIN
            service -> dl : 16. getSensor(sensorID)
            activate dl
                dl --> service : 17. s1 : Sensor
            deactivate dl

            service -> s1 : 18. getSensorNeighbours(Sensor)
            activate s1
                create "list[i] : list<Sensor>" as list
                s1 --> list : 19. <<create>>
                s1 --> service : 20. list
            deactivate s1

            loop Pour chaque voisin
                service -> list : 21. getMeasurements(l[i].id)
                activate list
                    list --> service : 22. Measurement
                deactivate list
            end
        
    service ->service : 23. analyse des données
    service --> cli : 24. capteur analysé comme frauduleux
    deactivate service

== Exclusion du capteur ==
admin -> cli : 25. excludeSensor(SensorID)
    cli -> adminservice : 26. excludeSensor(SensorID)
    activate adminservice
        adminservice -> dl : 27. getSensor(sensorID)
        activate dl
            dl --> adminservice : 28. s1 : Sensor
        deactivate dl

        adminservice -> uda : 29. addExcludedUser(s1.userId)
        activate uda
        adminservice --> cli : 30. Particulier exclut
        deactivate uda
    deactivate adminservice
deactivate cli
@enduml
