@startuml Partici
title Participation des utilisateurs à l'attribution de points aux particuliers

actor "Utilisateur" as user

participant "CLI" as cli

participant "AuthService" as auth
participant "AuthDataAccess" as authdata

participant "Statistics" as service

participant "PointsManager" as points
participant "DataLoader" as dl
participant "UserDataAccess" as uda

== Authentification d'un utilisateur ==
user -> cli : 1. Authentification
activate cli
cli -> auth : 2. login(login, mdp)

    activate auth
        auth -> authdata : 3. findCredential(login)

        activate authdata
            authdata -> auth : 4. Credentials
        deactivate authdata

        create "s :  Session(USER)" as s
        auth -> s : 5. <<create>>
        auth --> cli : 6. s
        cli --> user : 7. Authentification réussie

== Chargement des capteurs ==
    cli -> dl  : 8. loadData(s.userType)
    activate dl
    create "s1 : Sensor" as s1
    dl -> s1 : <<create>>
    dl --> cli  : 9. capteurs fiables et leurs mesures chargés
    deactivate dl

== Chargement des cleaners ==
    cli -> dl  : 10. loadData(s.userType)
    activate dl
    create "c1 : Cleaner" as c1
    dl -> c1 : <<create>>
    dl --> cli  : 11. purificateurs chargés
    deactivate dl

== Requête d’un utilisateur utilisant un capteur s1 ==
        user -> cli : 12. computeZone(lat, lng, period_start, period_end, radius)
        cli -> service : 13. computeZone(lat, lng, period_start, period_end, radius)
        
        activate service
            service -> auth : 14. checkRequiredRole(USER)
            auth --> service : 15. USER

            service -> dl : 16. getSensor(s1.id)
            activate dl
                dl --> service : 17. s1 : Sensor
            deactivate dl

            service -> s1 : 18. getMeasurements()
            activate s1
                s1 --> service : 19. list<Measurement>
            deactivate s1

            service -> service : 20. calcule moyenne AQI

            service -> points : 21. award(s1)
            activate points
                points -> uda : 22. updateUserPoints(s1.userId)
                activate uda
                    points --> service : 23. Points ajoutés
                deactivate uda
            deactivate points

            service --> cli : 24. AQI
        deactivate service
    deactivate auth
deactivate cli
@enduml