@startuml analyseCleaner
title Diagramme de Séquence – Analyse de l'impact d’un purificateur sur la qualité de l’air

actor "Fournisseur" as user

participant "CLI" as cli

participant "Authservice" as auth
participant "AuthDataAccess" as authdata

participant "Statistics" as service

participant "DataLoader" as dl

== Authentification d'un utilisateur ==
user -> cli : 1. Authentification
activate cli
cli -> auth : 2. login(login, mdp)

    activate auth
        auth -> authdata : 3. findCredential(login)

        activate authdata
            authdata -> auth : 4. Credentials
        deactivate authdata

        create "s :  Session(USER)" as s
        auth -> s : 5. <<create>>
        auth --> cli : 6. s
        cli --> user : 7. Authentification réussie

== Chargement des capteurs ==
    cli -> dl  : 8. loadData(s.userType)
    activate dl
    create "s1 : Sensor" as s1
    dl -> s1 : <<create>>
    dl --> cli  : 9. capteurs fiables et leurs mesures chargés
    deactivate dl

== Chargement des cleaners ==
    cli -> dl  : 10. loadData(s.userType)
    activate dl
    create "c1 : Cleaner" as c1
    dl -> c1 : <<create>>
    dl --> cli  : 11. purificateurs chargés
    deactivate dl

== Requête d’analyse ==
user -> cli : 12: analyzeCleaner(cleanerID, radius)

cli -> service : 13. analyzeCleaner(cleanerID, radius)
activate service
    service -> auth : 14. checkRequiredRole(FOURNISSEUR)
    auth --> service : 15. FOURNISSEUR
    == Récupération du purificateur ==
    service -> dl : 16. getCleaner(cleanerID)
    activate dl
        dl --> service : 17. c1 : Cleaner
    deactivate dl

    == Recherche des capteurs proches ==
    service -> c1 : 18. getNeighbouringSensors(radius)
    activate c1
        create "list[i] : list<Sensor>" as list
        c1 --> list : 19. <<create>>
        c1 --> service : 20. list
    deactivate c1

    == Récupération des mesures ==
    loop Pour chaque capteur
        service -> list : 21. getClosestMeasurements(activation_start, -1)
        activate list
            list --> service : 22. list<Measurement> (avant)
        deactivate list
        service -> list : 23. getClosestMeasurements(activation_end, 1)
        activate list
            list --> service : 24. list<Measurement> (après)
        deactivate list
    end

    == Calcul de l'amélioration ==
    service -> service : 25. Moyenne des mesures avant/après
    service -> service : 26. Calcul du pourcentage d’amélioration

    service --> cli : 27. Résultat (pourcentage par polluant)
deactivate service
deactivate cli

@enduml
