@startuml MCD

package "Données" {
    class Sensor {
    - id : string
    - lat : double
    - lng : double
    - measurements : vector<Measurement>
    - userId : string
    + distanceTo(lat : double, lng : double) : double
    + getSensorNeighbours(sensors : vector<Sensor>*, radius : int) : vector<Sensor>
    + getMeasurements(period_start : DateTime, period_end : DateTime) : vector<Measurement>
    + getClosestMeasurements(instant : DateTime, before_after : int) : vector<Measurement>
    }

    class Measurement {
    - ts : DateTime
    - attr_id : string
    - attr_unit : string
    - attr_desc : string
    - value : double
    + isWithin(period_start : DateTime, period_end : DateTime) : bool
    }

    class Cleaner {
    - id : string
    - lat : double
    - lng : double
    - start : DateTime
    - end  : DateTime
    + getNeighbouringSensors(radius : int, sensors : vector<Sensor>*) : vector<Sensor>
    }

    class Credentials {
    - login : string
    - password : string
    - userType : UserType
    - userId : string
    }

    class ParticulierData {
    - id : string
    - points : int
    - isExcluded : bool
    }
}


package "Services" {
    class Statistics {
    - vector<Sensor>* sensors
    - vector<Cleaner>* cleaners
    - PointsManager* pointsManager
    - AuthService* authService
    + analyzeSensor(sensorID: string) : int
    + analyzeCleaner(cleanerID: string, radius : int) : vector<Measurement>
    + computeZone(lat : double, lng : double, period_start : DateTime, period_end : DateTime, radius : int) : vector<Measurement>
    + compareSensors(sensorID: string, period_start : DateTime, period_end : DateTime) : vector<Sensor>
    + extrapolateAQI(lat : double, lng : double, period_start : DateTime, period_end : DateTime, radiusExtrapolation : int) : vector<Measurement>
    + getSensorById(id : string) : Sensor*
    + getCleanerById(id : string) : Cleaner*
    }

    class PointsManager {
    - UserDataAccess uda
    - vector<Sensor>* sensors
    - vector<ParticulierData>* particulierData
    - AuthService* authService
    + award(sensorsUsed : vector<string>) : bool
    + getPoints(userId : string) : int
    }

    class AdminServices {
    - UserDataAccess uda
    - vector<Sensor>* sensors
    - AuthService* authService
    + excludeSensor(sensorID: string)
    + evaluate(stats : Statistics*) : vector<double>
    }

    package "Authentification" {
        enum UserType {
        - Admin
        - User
        - Particulier
        - Fournisseur
        - Undefined
        }

        class Session {
        - userType : UserType
        - userId : string
        }

        class AuthService {
        - currentSession : Session
        + login(databasePath : string, login : string, password : string) : Session
        + checkRequiredRole(role : UserType) : bool
        + setCurrentSession(userType : UserType, userid : string) : bool
        }
    }
}


package "Accès aux données" {
    class DataLoader {
    - sensors : vector<Sensor>
    - cleaners : vector<Cleaner>
    + loadSensor(databasePath : string) : vector<Sensor>*
    + loadCleaner(databasePath : string) : vector<Cleaner>*
    }

    class UserDataAccess {
    + initializeCSVFile(filename : string) : bool
    + loadParticulierData() : vector<ParticulierData>
    + updateUserPoints(userId : string)
    + addExcludedUser(userId : string)
    }

    class AuthDataAccess {
    + findCredentials(databasePath : string, login : string, password : string) : Credentials
    }
}


package "Interface utilisateur" {
    class CLI {
    + run()
    }
}



Sensor  o-- Measurement

CLI --> AuthService

Statistics     ..> AuthService : checkRequiredRole
PointsManager  ..> AuthService : checkRequiredRole
AdminServices  ..> AuthService : checkRequiredRole

Statistics     ..> Cleaner
Statistics     ..> Sensor
PointsManager  ..> Sensor
AdminServices  ..> Sensor

AuthService ..> Credentials
@enduml